import { MetadataRoute } from 'next';
import { doctors } from '@/data/static-data';
import { IMPLANTOLOGY_DIRECTION_SLUGS } from '@/data/abramov/implantologyDirectionPages';
import { ORTHO_DIRECTION_SLUGS } from '@/data/goncharenko/orthoDirectionPages';
import { PRIORITY_SEO_ARTICLES } from '@/data/priority-seo-articles';
import { BLOG_TOPIC_SLUGS } from '@/data/blog-topic-pages';
import { PEDIATRIC_PROMOTIONS } from '@/data/pediatric-promotions';

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://altamed-c.ru';
  const now = new Date();

  const make = (path: string, changeFrequency: MetadataRoute.Sitemap[number]['changeFrequency'], priority: number) => ({
    url: `${baseUrl}${path === '/' ? '' : path}`,
    lastModified: now,
    changeFrequency,
    priority,
  });

  // Все пользовательские статические страницы (собраны из src/app/**/page.tsx)
  // Исключены: /search, /call-center, /admin/* и любые динамические [...] маршруты.
  const staticUserPaths: string[] = [
    '/',
    '/about',
    '/appointments',
    // Публичные статьи теперь доступны как /blog/<slug> (а /articles/<slug> — технический маршрут)
    '/blog/biopsiya-sheyki-matki-kogda-naznachayut-i-bolno-li-eto',
    '/blog/bol-vnizu-zhivota-u-zhenshchin-prichiny',
    '/blog/chto-pokazyvaet-kolposkopiya-i-kogda-ee-naznachayut',
    '/blog/chto-pokazyvayut-mazki-u-ginekologa-i-kogda-ih-naznachayut',
    '/blog/dopplerometriya-pri-beremennosti-kogda-naznachayut-i-chto-pokazyvaet',
    '/blog/endometrioz-simptomy-kogda-obraschatsya-i-kak-prohodit-lechenie',
    '/blog/ginekolog-ili-ginekolog-endokrinolog',
    '/blog/kak-podgotovitsya-k-priyomu-ginekologa',
    '/blog/kogda-nuzhno-zapisatsya-k-ginekologu-10-simptomov',
    '/blog/kontrastnaya-ehohisterosalpingoskopiya-chto-pokazyvaet-issledovanie',
    '/blog/kriodestrukciya-sheyki-matki-kogda-primenyaetsya-i-chto-vazhno-znat',
    '/blog/lechenie-zabolevaniy-sheyki-matki-kakie-metody-primenyayutsya',
    '/blog/narushenie-menstrualnogo-tsikla',
    '/blog/pajpel-biopsiya-endometriya-chto-eto-kogda-nuzhna-i-kak-prohodit',
    '/blog/pervyy-priem-beremennoy-kak-prohodit-konsultatsiya',
    '/blog/podgotovka-k-beremennosti-kakie-obsledovaniya-mogut-ponadobitsya',
    '/blog/podgotovka-k-eko-zachem-nuzhna-konsultatsiya-akushera-ginekologa',
    '/blog/polipy-v-ginekologii-kogda-nuzhno-udalenie-i-kak-prohodit-procedura',
    '/blog/poslerodovyy-osmotr-u-ginekologa-kogda-prihodit-i-chto-proveryayut',
    '/blog/profilakticheskiy-osmotr-ginekologa-kakie-obsledovaniya-mogut-ponadobitsya',
    '/blog/radiovolnovaya-biopsiya-sheyki-matki-osobennosti-procedury',
    '/blog/udalenie-kondilom-i-papillom-v-intimnoy-zone-kogda-obraschatsya-k-vrachu',
    '/blog/uzi-pri-beremennosti-kogda-delat-i-chto-pokazyvaet-issledovanie',
    '/blog/vaginit-simptomy-prichiny-i-kogda-nuzhna-konsultatsiya-ginekologa',
    '/blog/kak-prohodit-vedenie-beremennosti',
    '/blog/vnutrimatochnaya-spiral-ustanovka-i-udalenie',
    '/blog/vydeleniya-zud-zhzhenie-kogda-k-ginekologu',
    '/blog/kogda-stoit-obratitsya-k-allergologu',
    '/blog/allergoproby-kak-prohodyat-i-kogda-nuzhny',
    '/blog/sezonnaya-allergiya-simptomy-i-kogda-zapisyvatsya',
    '/blog/allergiya-u-detej-s-kakimi-simptomami-obrashchatsya',
    '/blog/kak-podgotovitsya-k-priemu-allergologa',
    '/blog/kogda-stoit-obratitsya-k-gastroenterologu',
    '/blog/bol-v-zhivote-kogda-nuzhen-gastroenterolog',
    '/blog/izzhoga-i-otryzhka-kogda-pora-zapisatsya-k-gastroenterologu',
    '/blog/helicobacter-pylori-kogda-vrach-mozhet-rekomendovat-dyhatelnyj-test',
    '/blog/vzdutie-zhivota-i-meteorizm',
    '/blog/zapor-ili-diareya',
    '/blog/13s-ureaznyj-dyhatelnyj-test',
    '/blog/kogda-stoit-obratitsya-k-dermatologu',
    '/blog/syp-i-zud-kogda-nuzhen-vrach',
    '/blog/akne-u-podrostkov-i-vzroslyh-kogda-idti-k-dermatologu',
    '/blog/rodinki-i-dermatoskopiya-kogda-nuzhno-proverit-obrazovanie',
    '/blog/gribok-nogtej-simptomy-i-diagnostika',
    '/blog/atopicheskiy-dermatit-u-detej',
    '/blog/psoriaz-kogda-nuzhna-konsultatsiya-dermatologa',
    '/blog/ekzema-i-dermatit-v-chem-raznitsa-dlya-patsienta',
    '/blog/borodavki-i-papillomy-mozhno-li-udalyat-samostoyatelno',
    '/blog/kontagioznyy-mollyusk-u-detej-i-vzroslyh',
    '/blog/perhot-i-zud-kozhi-golovy',
    '/blog/kak-podgotovitsya-k-priyomu-dermatologa',
    '/blog/kogda-stoit-obratitsya-k-lor-vrachu',
    '/blog/bol-v-uhe-kogda-nuzhen-otolaringolog',
    '/blog/sernaya-probka-simptomy-i-udalenie',
    '/blog/nasmork-i-zalozhennost-nosa-kogda-idti-k-loru',
    '/blog/sinusit-simptomy-i-diagnostika',
    '/blog/chastye-anginy-i-probki-v-mindalinah',
    '/blog/osiplost-golosa-kogda-nuzhna-laringoskopiya',
    '/blog/proverka-slukha-audiometriya-i-timpanometriya',
    '/blog/lor-dlya-rebenka-chastye-otity-hrap-i-nasmork',
    '/blog/nosovoe-krovotechenie-kogda-nuzhna-pomoshch',
    '/blog/promyvanie-lakun-mindalin-komu-naznachayut',
    '/blog/inorodnoe-telo-v-uhe-ili-nosu-chto-delat',
    '/blog/kogda-stoit-obratitsya-k-nevrologu',
    '/blog/golovnaya-bol-kogda-nuzhen-nevrolog',
    '/blog/migren-simptomy-i-chto-obsudit-s-vrachom',
    '/blog/bol-v-spine-kogda-nuzhna-konsultatsiya-nevrologa',
    '/blog/bol-v-shee-i-onemenie-ruk',
    '/blog/onemenie-nog-i-murashki-vozmozhnye-prichiny',
    '/blog/golovokruzhenie-nevrolog-ili-lor',
    '/blog/narusheniya-sna-i-trevozhnost-kogda-obraschatsya-k-vrachu',
    '/blog/vosstanovlenie-posle-insulta-rol-nevrologa',
    '/blog/chto-vzyat-na-priyom-k-nevrologu',
    '/blog/kogda-mrt-deystvitelno-nuzhno',
    '/blog/refleksoterapiya-kogda-ee-mozhet-naznachit-vrach',
    '/blog/kogda-stoit-obratitsya-k-mammologu',
    '/blog/uplotnenie-v-grudi-chto-delat',
    '/blog/bol-v-molochnoj-zheleze-kogda-nuzhen-vrach',
    '/blog/vydeleniya-iz-soska-prichiny-i-diagnostika',
    '/blog/uzi-molochnyh-zhelez-kogda-naznachayut',
    '/blog/mammografiya-komu-i-kogda-nuzhna',
    '/blog/proverka-grudi-posle-40-let',
    '/blog/kista-molochnoj-zhelezy-chto-vazhno-znat',
    '/blog/fibroadenoma-nablyudenie-ili-lechenie',
    '/blog/mastopatiya-simptomy-i-konsultatsiya-vracha',
    '/blog/mammolog-posle-rodov-i-grudnogo-vskarmlivaniya',
    '/blog/kak-podgotovitsya-k-priemu-mammologa',
    '/blog/kogda-stoit-obratitsya-k-kardiologu',
    '/blog/povyshennoe-davlenie-kogda-nuzhen-vrach',
    '/blog/bol-v-grudi-kogda-nelzya-zhdat',
    '/blog/pereboi-v-serdtse-chto-mozhet-naznachit-kardiolog',
    '/blog/ekg-kogda-nuzhno-delat-i-chto-pokazyvaet',
    '/blog/holter-ekg-komu-naznachayut-i-kak-prohodit',
    '/blog/odyshka-pri-nagruzke-serdechnye-prichiny-i-diagnostika',
    '/blog/kak-pravilno-vesti-dnevnik-davleniya',
    '/blog/vysokiy-puls-kogda-obraschatsya-k-vrachu',
    '/blog/profilakticheskiy-osmotr-u-kardiologa-posle-40-let',
    '/blog/chto-vzyat-na-priem-k-kardiologu',
    '/blog/gipertonicheskiy-kriz-trevozhnye-simptomy',
    '/blog/kogda-stoit-obratitsya-k-oftalmologu',
    '/blog/suhost-i-ustalost-glaz-kogda-nuzhen-vrach',
    '/blog/mushki-i-vspyshki-pered-glazami-kogda-eto-opasno',
    '/blog/proverka-zreniya-i-podbor-ochkov-kak-prohodit-priem',
    '/blog/osmotr-glaz-pri-sakharnom-diabete',
    '/blog/vnutriglaznoe-davlenie-zachem-ego-izmerjajut',
    '/blog/kontaktnye-linzy-kogda-nuzhna-konsultatsiya-oftalmologa',
    '/blog/pokrasnenie-glaza-kogda-ne-stoit-lechitsya-samostoyatelno',
    '/blog/kogda-stoit-obratitsya-k-pediatru',
    '/blog/temperatura-u-rebenka-kogda-nuzhen-vrach',
    '/blog/kashly-u-rebenka-kogda-obrashchatsya-k-pediatru',
    '/blog/rvota-i-diareya-u-rebenka-priznaki-obezvozhivaniya',
    '/blog/vaktsinatsiya-rebenka-chto-obsudit-s-pediatrom',
    '/blog/spravka-v-sad-ili-shkolu-kak-prohodit-osmotr',
    '/blog/chastye-orvi-u-detej-kogda-nuzhna-konsultatsiya',
    '/blog/prikorm-i-pitanie-rebenka-voprosy-pediatru',
    '/blog/syp-u-rebenka-kogda-nuzhna-ochnaya-konsultatsiya',
    '/blog/planovyy-osmotr-rebenka-zachem-on-nuzhen',
    '/blog/kogda-stoit-obratitsya-k-proktologu',
    '/blog/krov-posle-stula-kogda-nuzhen-vrach',
    '/blog/gemorroj-simptomy-i-metody-lecheniya',
    '/blog/analnaya-treshchina-pochemu-bolno-posle-stula',
    '/blog/zapor-u-vzroslyh-kogda-nuzhen-proktolog',
    '/blog/zud-i-zhzhenie-v-zadnem-prohode',
    '/blog/paraprotsit-simptomy-pri-kotoryh-nelzya-zhdat',
    '/blog/svish-pryamoj-kishki-pochemu-vospalenie-vozvrashchaetsya',
    '/blog/koptchikovyj-hod-chto-delat-pri-boli-i-vydeleniyah',
    '/blog/rektoromanoskopiya-kogda-naznachayut-i-kak-podgotovitsya',
    '/blog/lateksnoe-ligirovanie-gemorroja-chto-vazhno-znat',
    '/blog/skleroterapiya-gemorrooidalnyh-uzlov',
    '/blog/udalenie-analnyh-bakhromok-kogda-provoditsya',
    '/blog/polip-pryamoj-kishki-pochemu-vazhno-obsledovanie',
    '/blog/ozonoterapiya-kak-prohodit-protsedura',
    '/blog/osteopaticheskiy-priem-kak-podgotovitsya',
    '/blog/detskiy-osteopat-kak-prohodit-priem',
    '/blog/allergiya',
    '/blog/gastrit',
    '/blog/schitovidnaya-zheleza',
    '/blog/oteki-nog',
    '/blog/pyatochnaya-shpora',
    '/blog/zubnaya-bol',
    '/blog/bol-v-gorle',
    '/blog/topics/gynecology',
    '/blog/topics/allergology',
    '/blog/topics/gastroenterology',
    '/blog/topics/dermatology',
    '/blog/topics/cardiology',
    '/blog/topics/mammology',
    '/blog/topics/neurology',
    '/blog/topics/otolaryngology',
    '/blog/topics/ophthalmology',
    '/blog/topics/pediatrics',
    '/blog/topics/proctology',
    '/blog/topics/rehabilitation',
    '/blog/topics/endocrinology',
    '/blog/topics/therapy',
    '/blog/topics/traumatology',
    '/blog/topics/dentistry',
    '/blog',
    '/contacts',
    '/diagnostics',
    '/doctor/abramov-implantolog',
    '/doctor/goncharenko-ortodont',
    '/doctors',
    '/ginekolog-v-odintsovo',
    '/ginekolog-v-odintsovo/akusher-ginekolog',
    '/ginekolog-v-odintsovo/priem-ginekologa',
    '/ginekolog-v-odintsovo/profilakticheskie-osmotry',
    '/ginekolog-v-odintsovo/vedenie-beremennosti',
    '/privacy-policy',
    '/promo',
    '/rehabilitation',
    '/schedule',
    '/services',
    '/services/airflow-prophylaxis-master',
    '/services/akusher-ginekolog-odintsovo',
    '/services/allergology',
    '/services/bioresonance',
    '/services/carboxytherapy',
    '/services/cardiology',
    '/services/ct',
    '/services/dentistry',
    '/services/dentistry/aesthetic',
    '/services/dentistry/braces',
    '/services/dentistry/cadcam',
    '/services/dentistry/caries',
    '/services/dentistry/constructions',
    '/services/dentistry/consultation',
    '/services/dentistry/ct',
    '/services/dentistry/deposits',
    '/services/dentistry/emergency',
    '/services/dentistry/extraction',
    '/services/dentistry/fixed-appliances',
    '/services/dentistry/general-diagnostics',
    '/services/dentistry/hygiene',
    '/services/dentistry/implantation',
    '/services/dentistry/orthodontic-maintenance',
    '/services/dentistry/orthodontics',
    '/services/dentistry/pediatric-dentistry',
    '/services/dentistry/periodontics',
    '/services/dentistry/plastic',
    '/services/dentistry/prosthetics',
    '/services/dentistry/prosthodontics',
    '/services/dentistry/removable-appliances',
    '/services/dentistry/strengthening',
    '/services/dentistry/surgery',
    '/services/dentistry/therapeutic',
    '/services/dentistry/xray',
    '/services/dentistry/xray-diagnostics',
    '/services/dermatology',
    '/services/dietetics',
    '/services/elgos-therapy',
    '/services/endocrinology',
    '/services/endoscopy',
    '/services/family-psychology',
    '/services/functional-diagnostics',
    '/services/gastroenterology',
    '/services/gnathology',
    '/services/gonkongskiy-gripp',
    '/services/hardware-diagnostics',
    '/services/hilt-laser',
    '/services/implantation',
    '/services/lab-tests',
    '/services/lab-tests/calculator',
    '/services/lab-tests/analizy-rebenku',
    '/services/laser-cosmetology',
    '/services/lymph-e-massage',
    '/services/mammology',
    '/services/massage',
    '/services/neurology',
    '/services/ophthalmology',
    '/services/osteopathy',
    '/services/osteopathy/pediatric',
    '/services/ozone-therapy',
    '/services/otolaryngology',
    '/services/pediatrics',
    '/services/physiotherapy',
    '/services/pregnancy-screening',
    '/services/priem-ginekologa-odintsovo',
    '/services/proctology',
    '/services/profilakticheskiy-osmotr-ginekologa-odintsovo',
    '/services/rentgenology',
    '/services/shockwave-therapy',
    '/services/sis-magnetotherapy',
    '/services/surdology',
    '/services/surgery',
    '/services/tekar-therapy',
    '/services/therapy',
    '/services/traumatology',
    '/services/ultrasound',
    '/services/urology',
    '/services/vacuum-massage',
    '/services/vedenie-beremennosti-odintsovo',
    '/services/xray',
  ];

  const staticUserPages: MetadataRoute.Sitemap = staticUserPaths.map((p) => {
    if (p === '/') return make('/', 'daily', 1.0);
    if (p === '/services' || p === '/doctors') return make(p, 'weekly', 0.9);
    if (p === '/contacts' || p === '/appointments' || p === '/promo' || p === '/blog') return make(p, 'weekly', 0.8);
    if (p === '/schedule') return make(p, 'daily', 0.7);
    if (p.startsWith('/ginekolog-v-odintsovo')) return make(p, 'weekly', 0.9);
    if (p.startsWith('/blog/')) return make(p, 'monthly', 0.8);
    return make(p, 'monthly', 0.6);
  });
  
  // Статические страницы
  const staticPages: MetadataRoute.Sitemap = staticUserPages;

  // Динамические страницы врачей
  const doctorPages: MetadataRoute.Sitemap = doctors.map((doctor) => ({
    url: `${baseUrl}/doctors/${doctor.slug}`,
    lastModified: now,
    changeFrequency: 'monthly' as const,
    priority: 0.8,
  }));

  // Динамические страницы акций
  const promoPages: MetadataRoute.Sitemap = [
    { id: 1, slug: 'promo-1' },
    { id: 2, slug: 'promo-2' },
    { id: 3, slug: 'promo-3' },
    { id: 4, slug: 'promo-4' },
    { id: 5, slug: 'promo-5' },
    { id: 6, slug: 'promo-6' },
    { id: 7, slug: 'promo-7' },
    ...PEDIATRIC_PROMOTIONS.map((promo, index) => ({ id: index + 8, slug: promo.slug })),
  ].map((promo) => ({
    url: `${baseUrl}/promo/${promo.slug}`,
    lastModified: now,
    changeFrequency: 'weekly' as const,
    priority: 0.7,
  }));

  // Динамические страницы направлений стоматологии (видит пользователь)
  const implantologyDirectionPages: MetadataRoute.Sitemap = IMPLANTOLOGY_DIRECTION_SLUGS.map((slug) => ({
    url: `${baseUrl}/services/dentistry/implantology/${slug}`,
    lastModified: now,
    changeFrequency: 'monthly' as const,
    priority: 0.6,
  }));

  const orthodonticsDirectionPages: MetadataRoute.Sitemap = ORTHO_DIRECTION_SLUGS.map((slug) => ({
    url: `${baseUrl}/services/dentistry/orthodontics/${slug}`,
    lastModified: now,
    changeFrequency: 'monthly' as const,
    priority: 0.6,
  }));

  const staticPathSet = new Set(staticUserPaths);
  const priorityArticlePages: MetadataRoute.Sitemap = Object.keys(PRIORITY_SEO_ARTICLES)
    .map((slug) => `/blog/${slug}`)
    .filter((path) => !staticPathSet.has(path))
    .map((path) => make(path, 'monthly', 0.8));
  const topicPages: MetadataRoute.Sitemap = BLOG_TOPIC_SLUGS
    .map((slug) => `/blog/topics/${slug}`)
    .filter((path) => !staticPathSet.has(path))
    .map((path) => make(path, 'monthly', 0.7));

  return [
    ...staticPages,
    ...doctorPages,
    ...promoPages,
    ...implantologyDirectionPages,
    ...orthodonticsDirectionPages,
    ...priorityArticlePages,
    ...topicPages,
  ];
}

